# Generated by Django 4.1.2 on 2022-10-25 10:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_promo_promo_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='photo',
            field=models.ImageField(default=1, upload_to=main.models.Promo.get_file_name),
            preserve_default=False,
        ),
    ]
