# Generated by Django 4.1.2 on 2022-10-28 14:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_paragraph_1_en_about_paragraph_1_uk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='info',
            name='main_background',
            field=models.ImageField(default=1, upload_to=main.models.Info.get_file_name),
            preserve_default=False,
        ),
    ]
