# Generated by Django 4.1.2 on 2022-10-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contacts_options_info_main_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='main_background',
        ),
    ]
