# Generated by Django 4.1.2 on 2022-10-31 14:36

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_info_main_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter phone number in format +xxx xx xxx xx xx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('email', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('is_processed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date', '-is_processed'),
            },
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description_en',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description_uk',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
    ]
