# Generated by Django 4.1.2 on 2022-11-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usermessage_alter_promo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='type',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week'), ('day', 'day'), ('місяця', 'місяця'), ('тижня', 'тижня'), ('дня', 'дня')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promo',
            name='type_en',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week'), ('day', 'day'), ('місяця', 'місяця'), ('тижня', 'тижня'), ('дня', 'дня')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='type_uk',
            field=models.CharField(choices=[('month', 'month'), ('week', 'week'), ('day', 'day'), ('місяця', 'місяця'), ('тижня', 'тижня'), ('дня', 'дня')], max_length=50, null=True),
        ),
    ]
